// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin_ai_settings from "./routes/admin/ai-settings.tsx";
import * as $admin_alerts from "./routes/admin/alerts.tsx";
import * as $admin_alerts_create from "./routes/admin/alerts/create.tsx";
import * as $admin_analytics from "./routes/admin/analytics.tsx";
import * as $admin_farms from "./routes/admin/farms.tsx";
import * as $admin_farms_id_ from "./routes/admin/farms/[id].tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_leads from "./routes/admin/leads.tsx";
import * as $admin_logs from "./routes/admin/logs.tsx";
import * as $admin_manufacturers from "./routes/admin/manufacturers.tsx";
import * as $admin_news from "./routes/admin/news.tsx";
import * as $admin_notifications from "./routes/admin/notifications.tsx";
import * as $admin_products_id_ from "./routes/admin/products/[id].tsx";
import * as $admin_products_create from "./routes/admin/products/create.tsx";
import * as $admin_products_index from "./routes/admin/products/index.tsx";
import * as $admin_schemes_id_edit from "./routes/admin/schemes/[id]/edit.tsx";
import * as $admin_schemes_create from "./routes/admin/schemes/create.tsx";
import * as $admin_schemes_index from "./routes/admin/schemes/index.tsx";
import * as $admin_sync from "./routes/admin/sync.tsx";
import * as $admin_users from "./routes/admin/users.tsx";
import * as $admin_users_id_ from "./routes/admin/users/[id].tsx";
import * as $admin_users_create from "./routes/admin/users/create.tsx";
import * as $api_admin_farms_id_verify from "./routes/api/admin/farms/[id]/verify.ts";
import * as $api_alerts_schedule from "./routes/api/alerts/schedule.ts";
import * as $api_analyze_crop from "./routes/api/analyze-crop.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_me from "./routes/api/auth/me.ts";
import * as $api_auth_profile from "./routes/api/auth/profile.ts";
import * as $api_bank_customers from "./routes/api/bank/customers.ts";
import * as $api_bank_loans from "./routes/api/bank/loans.ts";
import * as $api_bank_loans_id_ from "./routes/api/bank/loans/[id].ts";
import * as $api_bank_loans_id_repayments from "./routes/api/bank/loans/[id]/repayments.ts";
import * as $api_chat from "./routes/api/chat.ts";
import * as $api_crops_index from "./routes/api/crops/index.ts";
import * as $api_crops_recommend_farmId_ from "./routes/api/crops/recommend/[farmId].ts";
import * as $api_farms_id_ from "./routes/api/farms/[id].ts";
import * as $api_farms_id_alerts from "./routes/api/farms/[id]/alerts.ts";
import * as $api_farms_id_analyze from "./routes/api/farms/[id]/analyze.ts";
import * as $api_farms_id_export from "./routes/api/farms/[id]/export.ts";
import * as $api_farms_id_health from "./routes/api/farms/[id]/health.ts";
import * as $api_farms_id_observations from "./routes/api/farms/[id]/observations.ts";
import * as $api_farms_index from "./routes/api/farms/index.ts";
import * as $api_jobs_crawl_news from "./routes/api/jobs/crawl-news.ts";
import * as $api_jobs_index from "./routes/api/jobs/index.ts";
import * as $api_jobs_schedule from "./routes/api/jobs/schedule.ts";
import * as $api_leads_token_ from "./routes/api/leads/[token].ts";
import * as $api_push_register from "./routes/api/push/register.ts";
import * as $api_push_unregister from "./routes/api/push/unregister.ts";
import * as $api_recommendations_farmId_ from "./routes/api/recommendations/[farmId].ts";
import * as $api_scans_id_image from "./routes/api/scans/[id]/image.ts";
import * as $api_sync from "./routes/api/sync.ts";
import * as $api_test_db from "./routes/api/test-db.ts";
import * as $api_tickets_index from "./routes/api/tickets/index.ts";
import * as $api_voice_log from "./routes/api/voice-log.ts";
import * as $app_middleware from "./routes/app/_middleware.ts";
import * as $app_about from "./routes/app/about.tsx";
import * as $app_alerts from "./routes/app/alerts.tsx";
import * as $app_calendar from "./routes/app/calendar.tsx";
import * as $app_chat from "./routes/app/chat.tsx";
import * as $app_compare from "./routes/app/compare.tsx";
import * as $app_dealers from "./routes/app/dealers.tsx";
import * as $app_expert from "./routes/app/expert.tsx";
import * as $app_farm_id_ from "./routes/app/farm/[id].tsx";
import * as $app_farm_id_alerts from "./routes/app/farm/[id]/alerts.tsx";
import * as $app_farm_id_analyze from "./routes/app/farm/[id]/analyze.tsx";
import * as $app_farm_id_edit from "./routes/app/farm/[id]/edit.tsx";
import * as $app_farm_id_log from "./routes/app/farm/[id]/log.tsx";
import * as $app_farm_id_report from "./routes/app/farm/[id]/report.tsx";
import * as $app_farm_add from "./routes/app/farm/add.tsx";
import * as $app_farm_index from "./routes/app/farm/index.tsx";
import * as $app_farm_processing_id_ from "./routes/app/farm/processing/[id].tsx";
import * as $app_help from "./routes/app/help.tsx";
import * as $app_index from "./routes/app/index.tsx";
import * as $app_market from "./routes/app/market.tsx";
import * as $app_news from "./routes/app/news.tsx";
import * as $app_onboarding from "./routes/app/onboarding.tsx";
import * as $app_profile from "./routes/app/profile.tsx";
import * as $app_profile_edit from "./routes/app/profile/edit.tsx";
import * as $app_profile_notifications from "./routes/app/profile/notifications.tsx";
import * as $app_reports from "./routes/app/reports.tsx";
import * as $app_scan from "./routes/app/scan.tsx";
import * as $app_scan_history from "./routes/app/scan/history.tsx";
import * as $app_schemes from "./routes/app/schemes.tsx";
import * as $app_services from "./routes/app/services.tsx";
import * as $app_settings from "./routes/app/settings.tsx";
import * as $app_weather from "./routes/app/weather.tsx";
import * as $bank_assessment_id_ from "./routes/bank/assessment/[id].tsx";
import * as $bank_assessment_new from "./routes/bank/assessment/new.tsx";
import * as $bank_assessments_index from "./routes/bank/assessments/index.tsx";
import * as $bank_customers_id_ from "./routes/bank/customers/[id].tsx";
import * as $bank_customers_id_add_farm from "./routes/bank/customers/[id]/add-farm.tsx";
import * as $bank_customers_index from "./routes/bank/customers/index.tsx";
import * as $bank_customers_search from "./routes/bank/customers/search.tsx";
import * as $bank_emi_calculator from "./routes/bank/emi-calculator.tsx";
import * as $bank_index from "./routes/bank/index.tsx";
import * as $bank_loans_id_repayments from "./routes/bank/loans/[id]/repayments.tsx";
import * as $bank_portfolio from "./routes/bank/portfolio.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $AIAssistant from "./islands/AIAssistant.tsx";
import * as $BankFarmForm from "./islands/BankFarmForm.tsx";
import * as $CropRecommendations from "./islands/CropRecommendations.tsx";
import * as $EMICalculator from "./islands/EMICalculator.tsx";
import * as $ExpertTicketForm from "./islands/ExpertTicketForm.tsx";
import * as $FarmForm from "./islands/FarmForm.tsx";
import * as $FarmMap from "./islands/FarmMap.tsx";
import * as $FarmMapPreview from "./islands/FarmMapPreview.tsx";
import * as $FarmProcessing from "./islands/FarmProcessing.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $NDVIChart from "./islands/NDVIChart.tsx";
import * as $NotificationSettings from "./islands/NotificationSettings.tsx";
import * as $ProfileEditForm from "./islands/ProfileEditForm.tsx";
import * as $RepaymentForm from "./islands/RepaymentForm.tsx";
import * as $VoiceLogger from "./islands/VoiceLogger.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin/ai-settings.tsx": $admin_ai_settings,
    "./routes/admin/alerts.tsx": $admin_alerts,
    "./routes/admin/alerts/create.tsx": $admin_alerts_create,
    "./routes/admin/analytics.tsx": $admin_analytics,
    "./routes/admin/farms.tsx": $admin_farms,
    "./routes/admin/farms/[id].tsx": $admin_farms_id_,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/leads.tsx": $admin_leads,
    "./routes/admin/logs.tsx": $admin_logs,
    "./routes/admin/manufacturers.tsx": $admin_manufacturers,
    "./routes/admin/news.tsx": $admin_news,
    "./routes/admin/notifications.tsx": $admin_notifications,
    "./routes/admin/products/[id].tsx": $admin_products_id_,
    "./routes/admin/products/create.tsx": $admin_products_create,
    "./routes/admin/products/index.tsx": $admin_products_index,
    "./routes/admin/schemes/[id]/edit.tsx": $admin_schemes_id_edit,
    "./routes/admin/schemes/create.tsx": $admin_schemes_create,
    "./routes/admin/schemes/index.tsx": $admin_schemes_index,
    "./routes/admin/sync.tsx": $admin_sync,
    "./routes/admin/users.tsx": $admin_users,
    "./routes/admin/users/[id].tsx": $admin_users_id_,
    "./routes/admin/users/create.tsx": $admin_users_create,
    "./routes/api/admin/farms/[id]/verify.ts": $api_admin_farms_id_verify,
    "./routes/api/alerts/schedule.ts": $api_alerts_schedule,
    "./routes/api/analyze-crop.ts": $api_analyze_crop,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/me.ts": $api_auth_me,
    "./routes/api/auth/profile.ts": $api_auth_profile,
    "./routes/api/bank/customers.ts": $api_bank_customers,
    "./routes/api/bank/loans.ts": $api_bank_loans,
    "./routes/api/bank/loans/[id].ts": $api_bank_loans_id_,
    "./routes/api/bank/loans/[id]/repayments.ts": $api_bank_loans_id_repayments,
    "./routes/api/chat.ts": $api_chat,
    "./routes/api/crops/index.ts": $api_crops_index,
    "./routes/api/crops/recommend/[farmId].ts": $api_crops_recommend_farmId_,
    "./routes/api/farms/[id].ts": $api_farms_id_,
    "./routes/api/farms/[id]/alerts.ts": $api_farms_id_alerts,
    "./routes/api/farms/[id]/analyze.ts": $api_farms_id_analyze,
    "./routes/api/farms/[id]/export.ts": $api_farms_id_export,
    "./routes/api/farms/[id]/health.ts": $api_farms_id_health,
    "./routes/api/farms/[id]/observations.ts": $api_farms_id_observations,
    "./routes/api/farms/index.ts": $api_farms_index,
    "./routes/api/jobs/crawl-news.ts": $api_jobs_crawl_news,
    "./routes/api/jobs/index.ts": $api_jobs_index,
    "./routes/api/jobs/schedule.ts": $api_jobs_schedule,
    "./routes/api/leads/[token].ts": $api_leads_token_,
    "./routes/api/push/register.ts": $api_push_register,
    "./routes/api/push/unregister.ts": $api_push_unregister,
    "./routes/api/recommendations/[farmId].ts": $api_recommendations_farmId_,
    "./routes/api/scans/[id]/image.ts": $api_scans_id_image,
    "./routes/api/sync.ts": $api_sync,
    "./routes/api/test-db.ts": $api_test_db,
    "./routes/api/tickets/index.ts": $api_tickets_index,
    "./routes/api/voice-log.ts": $api_voice_log,
    "./routes/app/_middleware.ts": $app_middleware,
    "./routes/app/about.tsx": $app_about,
    "./routes/app/alerts.tsx": $app_alerts,
    "./routes/app/calendar.tsx": $app_calendar,
    "./routes/app/chat.tsx": $app_chat,
    "./routes/app/compare.tsx": $app_compare,
    "./routes/app/dealers.tsx": $app_dealers,
    "./routes/app/expert.tsx": $app_expert,
    "./routes/app/farm/[id].tsx": $app_farm_id_,
    "./routes/app/farm/[id]/alerts.tsx": $app_farm_id_alerts,
    "./routes/app/farm/[id]/analyze.tsx": $app_farm_id_analyze,
    "./routes/app/farm/[id]/edit.tsx": $app_farm_id_edit,
    "./routes/app/farm/[id]/log.tsx": $app_farm_id_log,
    "./routes/app/farm/[id]/report.tsx": $app_farm_id_report,
    "./routes/app/farm/add.tsx": $app_farm_add,
    "./routes/app/farm/index.tsx": $app_farm_index,
    "./routes/app/farm/processing/[id].tsx": $app_farm_processing_id_,
    "./routes/app/help.tsx": $app_help,
    "./routes/app/index.tsx": $app_index,
    "./routes/app/market.tsx": $app_market,
    "./routes/app/news.tsx": $app_news,
    "./routes/app/onboarding.tsx": $app_onboarding,
    "./routes/app/profile.tsx": $app_profile,
    "./routes/app/profile/edit.tsx": $app_profile_edit,
    "./routes/app/profile/notifications.tsx": $app_profile_notifications,
    "./routes/app/reports.tsx": $app_reports,
    "./routes/app/scan.tsx": $app_scan,
    "./routes/app/scan/history.tsx": $app_scan_history,
    "./routes/app/schemes.tsx": $app_schemes,
    "./routes/app/services.tsx": $app_services,
    "./routes/app/settings.tsx": $app_settings,
    "./routes/app/weather.tsx": $app_weather,
    "./routes/bank/assessment/[id].tsx": $bank_assessment_id_,
    "./routes/bank/assessment/new.tsx": $bank_assessment_new,
    "./routes/bank/assessments/index.tsx": $bank_assessments_index,
    "./routes/bank/customers/[id].tsx": $bank_customers_id_,
    "./routes/bank/customers/[id]/add-farm.tsx": $bank_customers_id_add_farm,
    "./routes/bank/customers/index.tsx": $bank_customers_index,
    "./routes/bank/customers/search.tsx": $bank_customers_search,
    "./routes/bank/emi-calculator.tsx": $bank_emi_calculator,
    "./routes/bank/index.tsx": $bank_index,
    "./routes/bank/loans/[id]/repayments.tsx": $bank_loans_id_repayments,
    "./routes/bank/portfolio.tsx": $bank_portfolio,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/AIAssistant.tsx": $AIAssistant,
    "./islands/BankFarmForm.tsx": $BankFarmForm,
    "./islands/CropRecommendations.tsx": $CropRecommendations,
    "./islands/EMICalculator.tsx": $EMICalculator,
    "./islands/ExpertTicketForm.tsx": $ExpertTicketForm,
    "./islands/FarmForm.tsx": $FarmForm,
    "./islands/FarmMap.tsx": $FarmMap,
    "./islands/FarmMapPreview.tsx": $FarmMapPreview,
    "./islands/FarmProcessing.tsx": $FarmProcessing,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/NDVIChart.tsx": $NDVIChart,
    "./islands/NotificationSettings.tsx": $NotificationSettings,
    "./islands/ProfileEditForm.tsx": $ProfileEditForm,
    "./islands/RepaymentForm.tsx": $RepaymentForm,
    "./islands/VoiceLogger.tsx": $VoiceLogger,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
